# build:
#   no_build: true

# Custom section is used to store configurations that might be repetative.
# Please read YAML documentation for details on how to use substitutions and anchors.
custom:

  email_notifications_props: &email_notifications_props
    email_notifications:
      on_failure:
        - richard@ontargetcomputing.net 

  basic-cluster-props: &basic-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"

  ci-cluster: &ci-cluster
    new_cluster:
      <<: *basic-cluster-props
      num_workers: 1
      cluser_id: "0124-003646-pqv9062d"
      node_type_id: "Standard_DS3_v2"



environments:
  ci:
    workflows:
      # - name: "hello-world-job"
      #   <<: 
      #     - *email_notifications_props
      #   <<: *ci-cluster
      #   spark_python_task:
      #     python_file: "file://cdii_data_pipelines/hello_world.py"

    - name: "New Wildfire Pipeline"
      tasks:
        - task_key: "points_bronze"
          existing_cluster_name: "Richard's Cluster"
          spark_python_task:
            python_file: "file://cdii_data_pipelines/tasks/bronze_task.py"
            parameters: [ "--conf-file", "file:fuse://conf/tasks/hazard/wildfire/bronze_points_task.ci.yml" ]
        - task_key: "perims_bronze"
          existing_cluster_name: "Richard's Cluster"
          spark_python_task:
            python_file: "file://cdii_data_pipelines/tasks/bronze_task.py"
            parameters: [ "--conf-file", "file:fuse://conf/tasks/hazard/wildfire/bronze_perims_task.ci.yml" ]
        - task_key: "silver"
          existing_cluster_name: "Richard's Cluster"
          depends_on: 
            - task_key:  points_bronze
            - task_key:  perims_bronze
          spark_python_task:
            python_file: "file://cdii_data_pipelines/tasks/hazard/wildfire/silver_task.py"
            parameters: [ "--conf-file", "file:fuse://conf/tasks/hazard/wildfire/silver_task.ci.yml" ]
        - task_key: "gold"
          existing_cluster_name: "Richard's Cluster"
          depends_on: 
            - task_key:  silver
          spark_python_task:
            python_file: "file://cdii_data_pipelines/tasks/hazard/wildfire/wildfire_gold.py"
        - task_key: "green"
          existing_cluster_name: "Richard's Cluster"
          depends_on: 
            - task_key:  gold
          spark_python_task:
            python_file: "file://cdii_data_pipelines/tasks/hazard/wildfire/wildfire_green.py"            